#!/usr/bin/env ruby
# frozen_string_literal: true
require_relative '../lib/alemax/cli'

Signal.trap('INT') do
  warn("\n#{caller.join("\n")}: interrupted")
  exit(1)
end

begin
  Alemax::CLI.start
rescue Alemax::CLI::Error => err
  puts "ERROR: #{err.message}"
  exit 1
end
